### ISSUE TITLE
State clearly how my data is stored and used

### ISSUE THREAD

**Issue by pllk** [UniversityOfHelsinkiCS/gptwrapper#21]
I'm not sure what happens when I enter data to Curre Chat. I would assume it is not stored or used to train the model, but is that true?

At the moment there is the following warning but it is not clear if the data is stored or used. If it is not stored or used, why shouldn't I send copyrighted data to the system? If it is stored or used, it would be good to mention this clearly. 

"Kun käytät tekoälytyökaluja, vältä tietojen jakamista, joiden jakamisen luvallisuudesta sinulla ei ole varmuutta. Kun syötät tietoja tekoälytyökaluun, varmista, että otat huomioon mahdolliset luottamuksellisuusrajoitukset ja olet hankkinut tarvittavat tekijänoikeusluvat jne. annettujen tietojen jakamiseksi. Minkä tahansa luvattoman tiedon käyttö tekoälyjärjestelmissä voi johtaa kolmansien osapuolien immateriaalioikeuksien loukkaamiseen."

**Comment by Keskimaki** [comment]
Now that the language models are running on the university's Azure instance this has been clarified in the info message

"CurreChat käyttää OpenAI:n kehittämiä suuria kielimalleja, jotka sijaitsevat Helsingin yliopiston Microsoft Azure -pilvipalvelussa EU-alueella. Palveluun syötettyjä tietoja ei käytetä kielimallin jatkokouluttamiseen. Käyttäjistä ei myöskään välity tunnistetietoja kielimallille."
