### ISSUE TITLE
Misleading alert message when uploading unsupported file type

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/gptwrapper#84]
now you can try to attach anything

<img width="815" alt="image" src="https://github.com/UniversityOfHelsinkiCS/gptwrapper/assets/523235/77393cde-a451-4c05-a684-beaf1a0e815e">

the error message a bit misleading

<img width="563" alt="image" src="https://github.com/UniversityOfHelsinkiCS/gptwrapper/assets/523235/b24f3ec3-241f-40d5-a791-6b012c1b209e">

**Comment by Catrovitch** [comment]
Let's split issue into sub-parts. First we solve the misleading alert message.

**Comment by Catrovitch** [comment]
Message updated
